### ISSUE TITLE
支持。很好用

### ISSUE THREAD

**Issue by sunteta** [Misaka-blog/acme-1key#3]
非常感谢作者

支持。很好用

能加入阿里云的支持么？

**Comment by misakano7545** [comment]
@sunteta 只要不是国内的服务器都支持的

**Comment by sunteta** [comment]
不是加入 API 支持了阿里云和腾讯云。支持你的发展，我在其它项目上默默的推广了
https://github.com/bjdgyc/anylink/issues/71   回复最后是我推广的。好东西一定要讲。

**Comment by misakano7545** [comment]
@sunteta 还没用过呢
